version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: task-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=secret
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tasks
  db:
    image: postgres
    container_name: task-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
    ports:
      - "5432:5432"
    volumes:
      - .data:/var/lib/postgresql/data

volumes:
  .data: